<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block mb-1">Judul</label><input type="text" name="title" value="{{ old('title', $gallery->title ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800" required></div>
<div><label class="block mb-1">Slug</label><input type="text" name="slug" value="{{ old('slug', $gallery->slug ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div><label class="block mb-1">Kategori</label><select name="category" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"><option value="kegiatan" @selected(old('category', $gallery->category ?? 'kegiatan')==='kegiatan')>Kegiatan</option><option value="produk" @selected(old('category', $gallery->category ?? '')==='produk')>Produk</option><option value="proses" @selected(old('category', $gallery->category ?? '')==='proses')>Proses</option><option value="lainnya" @selected(old('category', $gallery->category ?? '')==='lainnya')>Lainnya</option></select></div>
<div><label class="block mb-1">Tanggal Event</label><input type="date" name="event_date" value="{{ old('event_date', isset($gallery->event_date) ? $gallery->event_date->format('Y-m-d') : '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div><label class="block mb-1">Image Path</label><input type="text" name="image_path" value="{{ old('image_path', $gallery->image_path ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800" required></div>
<div><label class="block mb-1">Thumbnail Path</label><input type="text" name="thumbnail_path" value="{{ old('thumbnail_path', $gallery->thumbnail_path ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div class="md:col-span-2"><label class="block mb-1">Lokasi</label><input type="text" name="location" value="{{ old('location', $gallery->location ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div class="md:col-span-2"><label class="block mb-1">Deskripsi</label><textarea name="description" class="w-full rounded-xl border-slate-300 dark:bg-slate-800">{{ old('description', $gallery->description ?? '') }}</textarea></div>
<label class="inline-flex items-center gap-2"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $gallery->is_featured ?? false))><span>Featured</span></label>
</div>
