<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block mb-1">Judul</label><input type="text" name="title" value="{{ old('title', $article->title ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800" required></div>
<div><label class="block mb-1">Slug</label><input type="text" name="slug" value="{{ old('slug', $article->slug ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div><label class="block mb-1">Kategori</label><select name="category" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"><option value="berita" @selected(old('category', $article->category ?? 'berita')==='berita')>Berita</option><option value="edukasi" @selected(old('category', $article->category ?? '')==='edukasi')>Edukasi</option><option value="inspirasi" @selected(old('category', $article->category ?? '')==='inspirasi')>Inspirasi</option><option value="press" @selected(old('category', $article->category ?? '')==='press')>Press</option></select></div>
<div><label class="block mb-1">Status</label><select name="status" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"><option value="draft" @selected(old('status', $article->status ?? 'draft')==='draft')>Draft</option><option value="published" @selected(old('status', $article->status ?? '')==='published')>Published</option><option value="archived" @selected(old('status', $article->status ?? '')==='archived')>Archived</option></select></div>
<div><label class="block mb-1">Published At</label><input type="datetime-local" name="published_at" value="{{ old('published_at', isset($article->published_at) ? $article->published_at->format('Y-m-d\\TH:i') : '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div><label class="block mb-1">Featured Image</label><input type="text" name="featured_image" value="{{ old('featured_image', $article->featured_image ?? '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div class="md:col-span-2"><label class="block mb-1">Excerpt</label><textarea name="excerpt" class="w-full rounded-xl border-slate-300 dark:bg-slate-800">{{ old('excerpt', $article->excerpt ?? '') }}</textarea></div>
<div class="md:col-span-2"><label class="block mb-1">Tags (pisah koma)</label><input type="text" name="tags" value="{{ old('tags', isset($article) ? implode(', ', $article->tags ?? []) : '') }}" class="w-full rounded-xl border-slate-300 dark:bg-slate-800"></div>
<div class="md:col-span-2"><label class="block mb-1">Content</label><textarea name="content" rows="8" class="w-full rounded-xl border-slate-300 dark:bg-slate-800" required>{{ old('content', $article->content ?? '') }}</textarea></div>
</div>
